language: node_js
node_js:
- '6'
- '4'
deploy:
  provider: npm
  email: npm@loke.com.au
  api_key:
    secure: q4dV8wN5um9FIDJErKKj1o7oLMhmZ0AWc4axQhYyBnOBLKw8Gfr3XoGv8argbqXJhoAhUSrPicHXU/Myjo3SEJO2eZqV2zbNckNsuQoLuH/8lvJG+oEYOvvCePm246i7pDrHt+SAkJ5VWAVcuBz5OHWsE0D36u4/AEa7fWkIGyuQW/jJ6G7olH/iBCZNQ/KXsvE9/kGiKaL43r7bx22AdLkHxoBZ3j76iFRpdLgN/butp33Ph/JCZ42fSaAhBHaHuJyTfkxXbzyvy8wusQFqnlhUnvZ0idHgd0lDSG//y7WQa9qwjpgumg5VTlGWMHRhSFyrssKZMQn0GY84UBJunnKu46nKtfuX+zxSOwYmOQM55uwcT1U3fbrhlwKzSmf3O4FsfdIBH/xJeOMI2Ahm4hv5N8q/H2NUd128rcsXOtzcfMVnzbfMnI0uS1S8NgYVWo8iFD/G1ZhzZFFsg1Hls1SvLNplaFMAMo5bEQjMB1tGnoMIb0/4fjNo+w3Mjm6Qu9CZZTySYiAktba+MZOBRf3ZwQ4KuGf/fwodqDXoHhEqMt2UVSyKkjBIM9Gqr5iuZxEqFrcunaUZbBZL5htG3QbAL5cTms8gIyNOmefq+L0+wUN3F5+Li+wCLC/RoUdF6opFzsdDJ6rIDq3WBboLx5MlwTuFEFBHqd0ir/aVl2A=
  on:
    tags: true
    repo: LOKE/loke-http-rpc
